### ISSUE TITLE
Building Windows Binaries Throws Error

### ISSUE THREAD

**Issue by LanceGundersen** [stanglab/tbinge#10]
### Background

When building via electron-builder for all platforms it throws an error for the windows binary creation step. This error doesn't appear to be impeding the build process as the .exe produced installs and runs correctly.

## Machine Specs
OS: Elementary OS (Ubuntu 18.04)
Electron: v4.0.2
Electron Builder: v20.38.5
Node: v11.0.0
Yarn: v1.13.0
NPM: v6.7.0

## Error Output
```bash
$ yarn dist-all
yarn run v1.13.0
$ electron-builder -mwl
  • electron-builder version=20.38.5
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=builds/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=4.0.2 appOutDir=builds/mac
  • skipped macOS application code signing reason=supported only on macOS
  • building        target=macOS zip arch=x64 file=builds/tbinge-test-2.0.0-mac.zip
  • building        target=DMG arch=x64 file=builds/tbinge-test-2.0.0.dmg
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=4.0.2 appOutDir=builds/linux-unpacked
  • building        target=snap arch=x64 file=builds/tbinge-test_2.0.0_amd64.snap
  • building        target=AppImage arch=x64 file=builds/tbinge-test 2.0.0.AppImage
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=4.0.2 appOutDir=builds/win-unpacked
  • building        target=nsis file=builds/tbinge-test Setup 2.0.0.exe archs=x64 oneClick=true perMachine=false
Error: spawn hdiutil ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
From previous event:
    at _createStageDmg (/home/lance/Development/school/playground/node_modules/dmg-builder/out/dmg.js:360:26)
    at createStageDmg (/home/lance/Development/school/playground/node_modules/dmg-builder/out/dmg.js:348:26)
    at /home/lance/Development/school/playground/node_modules/dmg-builder/src/dmg.ts:35:27
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1581:14)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
From previous event:
    at DmgTarget.build (/home/lance/Development/school/playground/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at nonMasPromise.then.then (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/macPackager.ts:90:26)
    at processImmediate (timers.js:632:19)
From previous event:
    at /home/lance/Development/school/playground/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /home/lance/Development/school/playground/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/lance/Development/school/playground/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/lance/Development/school/playground/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:162:5)
From previous event:
    at Packager.doBuild (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/lance/Development/school/playground/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/lance/Development/school/playground/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/lance/Development/school/playground/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at Packager._build (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/lance/Development/school/playground/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/lance/Development/school/playground/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/lance/Development/school/playground/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/lance/Development/school/playground/node_modules/electron-builder/src/cli/cli.ts:46:19)
  • building block map blockMapFile=builds/tbinge-test Setup 2.0.0.exe.blockmap
  • building embedded block map file=builds/tbinge-test-2.0.0-mac.zip
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by LanceGundersen** [comment]
I read somewhere that it could be a mono requirement on my machine. I will test next week for that and see if it is. If it is I will make a fix and update the readme.

**Comment by LanceGundersen** [comment]
@Drbaltar can you confirm or deny this error on your machine? I am not getting it anymore with the latest development strategy.

**Comment by LanceGundersen** [comment]
Closing as latest builds have confirmed the issues are cleared.
