### ISSUE TITLE
 Unexpected literal in error position of callback

### ISSUE THREAD

**Issue by LanceGundersen** [stanglab/tbinge#45]
Linter is failing on the MediaList.vue autolinter didn't fix it. Capturing as I don't have time to look at this moment.

```
Module Warning (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
error: Unexpected literal in error position of callback (standard/no-callback-literal) at src/components/MediaList.vue:335:15:
  333 |               callback(trailers[0].key, this)
  334 |             } else {
> 335 |               callback('', this)
      |               ^
  336 |             }
  337 |           } else callback('', this)
  338 |         }


error: Unexpected literal in error position of callback (standard/no-callback-literal) at src/components/MediaList.vue:337:18:
  335 |               callback('', this)
  336 |             }
> 337 |           } else callback('', this)
      |                  ^
  338 |         }
  339 |       })
  340 |     },
```

**Comment by Drbaltar** [comment]
Added statements to the ignore the string literal callback rule. It is intended and not an actual error. This was corrected during most recent commit to 'development'.
